version: "2"

linters:
  enable:
    # Essential linters
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis (includes gosimple)
    - unused        # Check for unused code

    # Code quality
    - gocyclo       # Cyclomatic complexity
    - misspell      # Spell checking
    - revive        # Fast, configurable linter

    # Best practices
    - bodyclose     # HTTP response body close
    - errname       # Error naming conventions
    - errorlint     # Error wrapping
    - gosec         # Security issues

linters-settings:
  gocyclo:
    min-complexity: 15

  revive:
    rules:
      - name: exported
        disabled: false

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor

  exclude-rules:
    # Exclude error checks in main/tests
    - path: _test\.go
      linters:
        - errcheck
        - gosec
